---

- name: Install system dependencies
  apt:
    pkg: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - ruby-dev
    - libpq-dev

- name: Install bundler
  gem:
    name: bundler
    state: present

- name: Update the Graves source code
  git:
    repo: '{{ graves_repo }}'
    version: '{{ graves_branch }}'
    dest: '{{ graves_src }}'
    force: yes

- name: Bundle install
  command: bundle install
  args:
    chdir: '{{ graves_src }}'

- name: NPM install
  command: npm install
  args:
    chdir: "{{ graves_src }}"

- name: Bower install
  command: bower install --allow-root
  args:
    chdir: "{{ graves_src }}"

- name: Build the application
  command: grunt compile:min
  args:
    chdir: "{{ graves_src }}"
