---

- name: Install system dependencies
  apt:
    pkg: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - ruby-dev
    - libpq-dev

- name: Install bundler
  gem:
    name: bundler
    state: present

- name: Update the Graves source code
  git:
    repo: '{{ graves_repo }}'
    version: '{{ graves_branch }}'
    dest: '{{ graves_src }}'
    force: yes

- name: Install dependencies
  command: bundle install
  args:
    chdir: '{{ graves_src }}'
