---

- name: Provision the instance
  hosts: localhost
  gather_facts: False
  sudo_user: ubuntu

  vars_files:
    - vars/ec2.yml

  tasks:

    - name: Start the server
      register: servers
      ec2:

        exact_count: 1
        image: '{{ ec2_image }}'
        instance_type: '{{ ec2_instance_type }}'
        vpc_subnet_id: '{{ ec2_subnet_id }}'
        group: '{{ ec2_group }}'
        region: '{{ ec2_region }}'
        assign_public_ip: yes
        keypair: '{{ ec2_keypair }}'
        wait: yes

        volumes:
          - device_name: /dev/sda1
            volume_size: '{{ ec2_volume_size }}'

        instance_tags:
          Name: graves-ui
          graves: ui

        count_tag:
          graves: ui
