---

- name: Add the Node.js PPA
  apt_repository:
    repo: ppa:chris-lea/node.js
    update_cache: yes

- name: Install Node.js
  apt:
    pkg: nodejs
    state: latest

- name: Install global npm modules
  npm:
    name: '{{ item }}'
    global: yes
  with_items:
    - grunt-cli
    - bower
